package com.company;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;

/**
 * Created by syq3b on 11/17/2014.
 */
public class AutoGenerateData {
    public static void main(String[] args)throws IOException{
        PrintWriter writer = new PrintWriter("S.txt", "UTF-8");

        int sSize = Integer.parseInt(args[0]);
        int tSize = Integer.parseInt(args[1]);
        final int keyRange = Integer.parseInt(args[2]);

        ArrayList<String> birthPlace = new ArrayList<String>();
        String[] states = {"Alabama","Alaska","Nebraska","Arizona","Nevada","Arkansas","NewHampshire","California","NewJersey",
                "Colorado","NewMexico","Connecticut","NewYork","Delaware","NorthCarolina","Florida","NorthDakota","Georgia",
                "Ohio","Hawaii","Oklahoma","Idaho","Oregon","Illinois","Pennsylvania","Indiana","RhodeIsland","Iowa",
                "SouthCarolina","Kansas","SouthDakota","Kentucky","Tennessee","Louisiana","Texas","Maine","Utah","Maryland",
                "Vermont","Massachusetts", "Virginia","Michigan","Washington","Minnesota","WestVirginia","Mississippi",
                "Wisconsin","Missouri","Wyoming"};
        
        //populating to the birthPlace list
        Collections.addAll(birthPlace, states);

        for(int i = 0; i < sSize; i++){
            String line = new String("S");

            //generating random number from 1 to 10000000
            //general formula = random(max-min+1)+min
            Random rand = new Random();

            //id
            int randInt = rand.nextInt(keyRange)+1;
            line = line + " " + Integer.toString(randInt);

            //year
            int randYear = rand.nextInt(515)+1500;

            line = line + " " + Integer.toString(randYear);

            writer.println(line);
        }
        writer.close();

        writer = new PrintWriter("T.txt", "UTF-8");

        for(int i = 0; i < tSize; i++){
            String line = new String("T");

            //generating random number from 0 to 100
            //general formula = random(max-min+1)+min
            Random rand = new Random();
            int randInt = rand.nextInt(keyRange)+1;
            line = line + " " + Integer.toString(randInt);

            //select a random birth state
            int stateArraySize = birthPlace.size();
            randInt = rand.nextInt(stateArraySize);
            line = line + " " + birthPlace.get(randInt);

            writer.println(line);
        }
        writer.close();
    }
}
